// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
    }
    dependencies {
        // Add this for Navigation Safe Args
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:2.7.7"
    }
}

plugins {
    alias(libs.plugins.android.application) apply false
    id 'com.google.gms.google-services' version '4.4.4' apply false
}